function init(self)
	gui.set_text(gui.get_node("score"), "apanha a arma")
	gui.set_text(gui.get_node("life"), "Vidas: 3")
end

function on_message(self, message_id, message)
	if message_id == hash("atualizar_score") then
		gui.set_text(gui.get_node("score"), "Arma encontrada!")
	elseif message_id == hash("atualizar_vida") then
		gui.set_text(gui.get_node("life"), "Vidas: " .. message.valor)
	end
end
