function init(self)
	gui.set_text(gui.get_node("life"), "Vidas: 3")
	gui.set_text(gui.get_node("score"), "Apanha a moeda!")
end

function on_message(self, message_id, message)
	if message_id == hash("atualizar_score") then
		gui.set_text(gui.get_node("score"), "moeda encontrada!")
	elseif message_id == hash("atualizar_vida") then
		gui.set_text(gui.get_node("life"), "Vida: " .. message.valor)
	end
end

