components {
  id: "player"
  component: "/main/assets/scripts/player.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"player 508x491\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/assets/tiles/player.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"player\"\n"
  "mask: \"ground\"\n"
  "mask: \"enemy\"\n"
  "mask: \"item\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -8.0\n"
  "      y: -188.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: -0.7009225\n"
  "      w: 0.71323746\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -75.0\n"
  "      y: -93.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 18.0\n"
  "      y: 176.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.09596267\n"
  "      w: 0.99538493\n"
  "    }\n"
  "    index: 6\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -70.0\n"
  "      y: 81.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 9\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -89.0\n"
  "      y: 176.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: -0.18262741\n"
  "      w: 0.9831822\n"
  "    }\n"
  "    index: 10\n"
  "    count: 3\n"
  "  }\n"
  "  data: 50.759876\n"
  "  data: 110.089485\n"
  "  data: 62.336\n"
  "  data: 65.350105\n"
  "  data: 84.96696\n"
  "  data: 73.86667\n"
  "  data: 22.10688\n"
  "  data: 70.26397\n"
  "  data: 29.09514\n"
  "  data: 92.52444\n"
  "  data: 22.10688\n"
  "  data: 70.26397\n"
  "  data: 29.09514\n"
  "}\n"
  ""
}
